

@astronaut_1 = Astronaut.create!(name: "Adam", age: 35, job: "Pilot")
@astronaut_2 = Astronaut.create!(name: "Beatrix", age: 45, job: "Engineer")
@astronaut_3 = Astronaut.create!(name: "Colton", age: 55, job: "Cook")
@mission_1 = Mission.create!(title: "A", time_in_space: 10)
@mission_2 = Mission.create!(title: "B", time_in_space: 15)
@mission_3 = Mission.create!(title: "C", time_in_space: 20)
AstronautMission.create!(mission_id: @mission_1.id, astronaut_id: @astronaut_1.id)
AstronautMission.create!(mission_id: @mission_2.id, astronaut_id: @astronaut_1.id)
AstronautMission.create!(mission_id: @mission_3.id, astronaut_id: @astronaut_1.id)
AstronautMission.create!(mission_id: @mission_1.id, astronaut_id: @astronaut_2.id)
AstronautMission.create!(mission_id: @mission_2.id, astronaut_id: @astronaut_2.id)
AstronautMission.create!(mission_id: @mission_3.id, astronaut_id: @astronaut_2.id)
AstronautMission.create!(mission_id: @mission_2.id, astronaut_id: @astronaut_3.id)
AstronautMission.create!(mission_id: @mission_3.id, astronaut_id: @astronaut_3.id)
